'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { renderGoogleProductFeed, createGoogleProductFeedHandler } = require('../lib/google-product-feed.js');
const product = { id:'gid://shopify/Product/44', handle:'3-4-oz-football-jig', title:'Jig & Craw', descriptionHtml:'<p>Hand <strong>poured</strong> & tested\u0001.</p>', vendor:'Bass Binge', presentation:{kind:'ordinary'}, media:[{type:'image', image:{url:'https://cdn.example/jig?a=1&b=2'}}], options:[{name:'3/4 oz.'}], variants:[{id:'gid://shopify/ProductVariant/101', availableForSale:false, price:{amount:'5.50',currencyCode:'USD'}, selectedOptions:[{name:'3/4 oz.',value:'Green Pumpkin'}]}] };
function response() { return {headers:{},setHeader(k,v){this.headers[k]=v;},status(c){this.code=c;return this;},send(b){this.body=b;return this;}}; }
test('renders admitted variants with exact links, price, stock, custom color mapping, and XML escaping', () => { const xml=renderGoogleProductFeed({schemaVersion:2,products:[product]}); assert.match(xml,/<g:id>101<\/g:id>/); assert.match(xml,/<g:item_group_id>44<\/g:item_group_id>/); assert.match(xml,/products\/3-4-oz-football-jig\?variant=101/); assert.match(xml,/<g:price>5\.50 USD<\/g:price>/); assert.match(xml,/<g:availability>out_of_stock/); assert.match(xml,/<g:color>Green Pumpkin<\/g:color>/); assert.match(xml,/Jig &amp; Craw/); assert.doesNotMatch(xml,/\u0001/); });
test('excludes the hidden rattle add-on and returns 503 for an empty admitted catalog', async () => { const xml=renderGoogleProductFeed({schemaVersion:2,products:[product,{handle:'rattle',presentation:{kind:'hidden-add-on'},variants:[]}]}); assert.doesNotMatch(xml,/>rattle</); const old=console.error; console.error=()=>{}; const res=response(); await createGoogleProductFeedHandler({getCatalog:async()=>({schemaVersion:2,products:[]})})({method:'GET'},res); console.error=old; assert.equal(res.code,503); });
test('supports HEAD', async () => { const res=response(); await createGoogleProductFeedHandler({getCatalog:async()=>({schemaVersion:2,products:[product]})})({method:'HEAD'},res); assert.equal(res.code,200); assert.equal(res.body,''); });
